# Generated by Django 6.0.6 on 2026-06-09 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Bino nomi')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Bino kodi')),
                ('address', models.CharField(max_length=255, verbose_name='Manzil')),
                ('floors', models.PositiveSmallIntegerField(default=0, verbose_name='Qavatlar soni')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Bino',
                'verbose_name_plural': 'Binolar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, verbose_name='Xona raqami')),
                ('capacity', models.PositiveSmallIntegerField(default=0, verbose_name="Sig'imi")),
                ('room_type', models.CharField(choices=[('lecture', "Ma'ruza xonasi"), ('seminar', 'Seminar xonasi'), ('lab', 'Laboratoriya'), ('computer', 'Kompyuter xonasi'), ('conference', 'Konferensiya zali')], default='lecture', max_length=20, verbose_name='Xona turi')),
                ('has_projector', models.BooleanField(default=False, verbose_name='Proyektor')),
                ('has_computer', models.BooleanField(default=False, verbose_name='Kompyuter')),
                ('has_whiteboard', models.BooleanField(default=True, verbose_name='Doska')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='rooms.building', verbose_name='Bino')),
            ],
            options={
                'verbose_name': 'Xona',
                'verbose_name_plural': 'Xonalar',
                'ordering': ['building', 'number'],
            },
        ),
    ]
