# Generated by Django 5.0.3 on 2026-06-11 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['building__name', 'floor', 'number'], 'verbose_name': 'Xona', 'verbose_name_plural': 'Xonalar'},
        ),
        migrations.AddField(
            model_name='building',
            name='description',
            field=models.TextField(blank=True, verbose_name='Tavsif'),
        ),
        migrations.AddField(
            model_name='building',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='room',
            name='floor',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Qavat'),
        ),
        migrations.AddField(
            model_name='room',
            name='has_air_conditioner',
            field=models.BooleanField(default=False, verbose_name='Konditsioner'),
        ),
        migrations.AddField(
            model_name='room',
            name='has_wifi',
            field=models.BooleanField(default=False, verbose_name='Wi-Fi'),
        ),
        migrations.AddField(
            model_name='room',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='Mavjud'),
        ),
        migrations.AddField(
            model_name='room',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('lecture', "Ma'ruza xonasi"), ('seminar', 'Seminar xonasi'), ('lab', 'Laboratoriya'), ('computer', 'Kompyuter xonasi'), ('conference', 'Konferensiya zali'), ('office', 'Ofis'), ('library', 'Kutubxona'), ('sport', 'Sport zali')], default='lecture', max_length=20, verbose_name='Xona turi'),
        ),
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('building', 'number')},
        ),
    ]
