# Generated by Django 6.0.6 on 2026-06-09 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nomi')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Kodi')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('dean_name', models.CharField(blank=True, max_length=255, verbose_name='Dekan ismi')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('established_date', models.DateField(blank=True, null=True, verbose_name='Tashkil etilgan sana')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fakultet',
                'verbose_name_plural': 'Fakultetlar',
                'ordering': ['name'],
            },
        ),
    ]
