# Generated by Django 6.0.6 on 2026-06-09 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        ('subjects', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.PositiveSmallIntegerField(choices=[(1, '1-semestr'), (2, '2-semestr'), (3, '3-semestr'), (4, '4-semestr'), (5, '5-semestr'), (6, '6-semestr'), (7, '7-semestr'), (8, '8-semestr')], verbose_name='Semestr')),
                ('lecture_hours', models.PositiveIntegerField(default=0, verbose_name="Ma'ruza")),
                ('practical_hours', models.PositiveIntegerField(default=0, verbose_name='Amaliy')),
                ('rating_hours', models.PositiveIntegerField(default=0, verbose_name='Reyting')),
                ('academic_year', models.CharField(max_length=9, verbose_name="O'quv yili")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workloads', to='groups.academicgroup', verbose_name='Guruh')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workloads', to='subjects.subject', verbose_name='Fan')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workloads', to='teachers.teacher', verbose_name="O'qituvchi")),
            ],
            options={
                'verbose_name': "O'quv yuklamasi",
                'verbose_name_plural': "O'quv yuklamalari",
                'ordering': ['-academic_year', 'teacher', 'semester'],
                'unique_together': {('teacher', 'subject', 'group', 'semester', 'academic_year')},
            },
        ),
    ]
