# Generated by Django 5.0.3 on 2026-06-11 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workload', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workload',
            options={'ordering': ['-academic_year', 'teacher__user__last_name', 'semester'], 'verbose_name': "O'quv yuklamasi", 'verbose_name_plural': "O'quv yuklamalari"},
        ),
        migrations.RemoveField(
            model_name='workload',
            name='rating_hours',
        ),
        migrations.AddField(
            model_name='workload',
            name='independent_hours',
            field=models.PositiveIntegerField(default=0, verbose_name="Mustaqil ta'lim"),
        ),
        migrations.AddField(
            model_name='workload',
            name='lab_hours',
            field=models.PositiveIntegerField(default=0, verbose_name='Laboratoriya soatlari'),
        ),
        migrations.AddField(
            model_name='workload',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Izoh'),
        ),
        migrations.AlterField(
            model_name='workload',
            name='lecture_hours',
            field=models.PositiveIntegerField(default=0, verbose_name="Ma'ruza soatlari"),
        ),
        migrations.AlterField(
            model_name='workload',
            name='practical_hours',
            field=models.PositiveIntegerField(default=0, verbose_name='Amaliy soatlar'),
        ),
    ]
