# Generated by Django 6.0.6 on 2026-06-09 17:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_degree', models.CharField(choices=[('none', "Yo'q"), ('phd', 'PhD'), ('dsc', 'DSc'), ('professor', 'Professor')], default='none', max_length=20, verbose_name='Ilmiy daraja')),
                ('position', models.CharField(choices=[('teacher', "O'qituvchi"), ('senior_teacher', "Katta o'qituvchi"), ('docent', 'Dotsent'), ('professor', 'Professor'), ('head', 'Kafedra mudiri')], default='teacher', max_length=20, verbose_name='Lavozim')),
                ('employee_id', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Xodim ID')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('address', models.TextField(blank=True, verbose_name='Manzil')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name="Tug'ilgan sana")),
                ('photo', models.ImageField(blank=True, null=True, upload_to='teachers/', verbose_name='Rasm')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Ish boshlagan sana')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachers', to='departments.department', verbose_name='Kafedra')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': "O'qituvchi",
                'verbose_name_plural': "O'qituvchilar",
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
    ]
