# Generated by Django 6.0.6 on 2026-06-09 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        ('rooms', '0001_initial'),
        ('subjects', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.PositiveSmallIntegerField(choices=[(1, 'Dushanba'), (2, 'Seshanba'), (3, 'Chorshanba'), (4, 'Payshanba'), (5, 'Juma'), (6, 'Shanba')], verbose_name='Hafta kuni')),
                ('lesson_number', models.PositiveSmallIntegerField(choices=[(1, '08:30 - 10:00'), (2, '10:10 - 11:40'), (3, '11:50 - 13:20'), (4, '13:30 - 15:00'), (5, '15:10 - 16:40'), (6, '16:50 - 18:20'), (7, '18:30 - 20:00')], verbose_name='Juftlik')),
                ('lesson_type', models.CharField(choices=[('lecture', "Ma'ruza"), ('practical', 'Amaliy'), ('lab', 'Laboratoriya'), ('seminar', 'Seminar')], max_length=20, verbose_name='Dars turi')),
                ('subgroup', models.PositiveSmallIntegerField(default=1, verbose_name='Podgruppa')),
                ('week_type', models.CharField(choices=[('all', 'Har hafta'), ('odd', 'Toq haftalar'), ('even', 'Juft haftalar')], default='all', max_length=20, verbose_name='Hafta turi')),
                ('academic_year', models.CharField(max_length=9, verbose_name="O'quv yili")),
                ('semester', models.PositiveSmallIntegerField(verbose_name='Semestr')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='groups.academicgroup', verbose_name='Guruh')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.room', verbose_name='Xona')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.subject', verbose_name='Fan')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.teacher', verbose_name="O'qituvchi")),
            ],
            options={
                'verbose_name': 'Dars jadvali',
                'verbose_name_plural': 'Dars jadvallari',
                'ordering': ['day_of_week', 'lesson_number', 'group'],
            },
        ),
    ]
