# Generated by Django 5.0.3 on 2026-06-11 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_alter_academicgroup_options_academicgroup_language_and_more'),
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['day_of_week', 'lesson_number', 'group__name'], 'verbose_name': 'Dars jadvali', 'verbose_name_plural': 'Dars jadvallari'},
        ),
        migrations.AlterField(
            model_name='schedule',
            name='week_type',
            field=models.CharField(choices=[('all', 'Har hafta'), ('odd', 'Toq haftalar'), ('even', 'Juft haftalar')], default='all', max_length=10, verbose_name='Hafta turi'),
        ),
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together={('group', 'day_of_week', 'lesson_number', 'week_type')},
        ),
    ]
