# Generated by Django 6.0.6 on 2026-06-09 17:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Yaratish'), ('update', 'Tahrirlash'), ('delete', "O'chirish"), ('view', "Ko'rish"), ('export', 'Eksport'), ('login', 'Kirish'), ('logout', 'Chiqish')], max_length=50, verbose_name='Harakat')),
                ('model_name', models.CharField(max_length=100, verbose_name='Model nomi')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name="Ob'ekt ID")),
                ('object_repr', models.CharField(blank=True, max_length=200, verbose_name="Ob'ekt nomi")),
                ('changes', models.TextField(blank=True, verbose_name="O'zgarishlar")),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP manzil')),
                ('user_agent', models.CharField(blank=True, max_length=500, verbose_name="Brauzer ma'lumoti")),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Vaqt')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Audit log',
                'verbose_name_plural': 'Audit loglari',
                'ordering': ['-timestamp'],
            },
        ),
    ]
