# Generated by Django 6.0.6 on 2026-06-09 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        ('subjects', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkloadRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.PositiveSmallIntegerField(verbose_name='Semestr')),
                ('total_hours', models.PositiveIntegerField(verbose_name='Soatlar')),
                ('lecture_hours', models.PositiveIntegerField(default=0, verbose_name="Ma'ruza soatlari")),
                ('practical_hours', models.PositiveIntegerField(default=0, verbose_name='Amaliy soatlar')),
                ('lab_hours', models.PositiveIntegerField(default=0, verbose_name='Laboratoriya soatlari')),
                ('message', models.TextField(blank=True, verbose_name='Xabar')),
                ('request_type', models.CharField(choices=[('standard', 'Standart'), ('urgent', 'Shoshilinch')], default='standard', max_length=20, verbose_name='Tur')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('sent', 'Yuborilgan'), ('approved', 'Tasdiqlangan'), ('rejected', 'Rad etilgan'), ('completed', 'Bajarilgan')], default='pending', max_length=20, verbose_name='Holat')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Rad etish sababi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('from_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_requests', to='departments.department', verbose_name="Jo'natuvchi kafedra")),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.subject', verbose_name='Fan')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teachers.teacher', verbose_name="O'qituvchi")),
                ('to_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_requests', to='departments.department', verbose_name='Qabul qiluvchi kafedra')),
            ],
            options={
                'verbose_name': 'Talabnoma',
                'verbose_name_plural': 'Talabnomalar',
                'ordering': ['-created_at'],
            },
        ),
    ]
