# Generated by Django 5.0.3 on 2026-06-11 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0001_initial'),
        ('teachers', '0003_alter_teacher_options_teacher_birth_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workloadrequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_requests', to='teachers.teacher', verbose_name='Tasdiqlovchi'),
        ),
        migrations.AddField(
            model_name='workloadrequest',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_requests', to='teachers.teacher', verbose_name='Yaratuvchi'),
        ),
        migrations.AlterField(
            model_name='workloadrequest',
            name='request_type',
            field=models.CharField(choices=[('standard', 'Standart'), ('urgent', 'Shoshilinch'), ('exchange', 'Almashuv')], default='standard', max_length=20, verbose_name='Talabnoma turi'),
        ),
        migrations.AlterField(
            model_name='workloadrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Kutilmoqda'), ('sent', 'Yuborilgan'), ('approved', 'Tasdiqlangan'), ('rejected', 'Rad etilgan'), ('completed', 'Bajarilgan'), ('cancelled', 'Bekor qilingan')], default='pending', max_length=20, verbose_name='Holat'),
        ),
        migrations.AlterField(
            model_name='workloadrequest',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teachers.teacher', verbose_name="Taklif qilinayotgan o'qituvchi"),
        ),
        migrations.AlterField(
            model_name='workloadrequest',
            name='total_hours',
            field=models.PositiveIntegerField(verbose_name='Jami soatlar'),
        ),
    ]
