# Generated by Django 6.0.6 on 2026-06-09 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('faculties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nomli')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Kodi')),
                ('degree_type', models.CharField(choices=[('bakalavr', 'Bakalavr'), ('magistr', 'Magistr'), ('doktorantura', 'Doktorantura')], default='bakalavr', max_length=20, verbose_name='Daraja')),
                ('education_type', models.CharField(choices=[('kunduzgi', 'Kunduzgi'), ('sirtqi', 'Sirtqi'), ('kechki', 'Kechki'), ('masofaviy', 'Masofaviy')], max_length=20, verbose_name="Ta'lim shakli")),
                ('duration', models.PositiveSmallIntegerField(help_text='Muddat (oylarda)', verbose_name='Muddat')),
                ('credits', models.PositiveSmallIntegerField(default=0, verbose_name='Kreditlar')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specializations', to='faculties.faculty', verbose_name='Fakultet')),
            ],
            options={
                'verbose_name': 'Mutaxassislik',
                'verbose_name_plural': 'Mutaxassisliklar',
                'ordering': ['faculty', 'name'],
            },
        ),
    ]
