# Generated by Django 6.0.6 on 2026-06-09 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculties', '0001_initial'),
        ('specializations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specialization',
            options={'verbose_name': 'Mutaxassislik', 'verbose_name_plural': 'Mutaxassisliklar'},
        ),
        migrations.RemoveField(
            model_name='specialization',
            name='description',
        ),
        migrations.AlterField(
            model_name='specialization',
            name='credits',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='specialization',
            name='degree_type',
            field=models.CharField(choices=[('bakalavr', 'Bakalavr'), ('magistr', 'Magistr'), ('doktorantura', 'Doktorantura')], default='bakalavr', max_length=20),
        ),
        migrations.AlterField(
            model_name='specialization',
            name='duration',
            field=models.PositiveSmallIntegerField(help_text='Muddat (oylarda)'),
        ),
        migrations.AlterField(
            model_name='specialization',
            name='education_type',
            field=models.CharField(choices=[('kunduzgi', 'Kunduzgi'), ('sirtqi', 'Sirtqi'), ('kechki', 'Kechki'), ('masofaviy', 'Masofaviy')], max_length=20),
        ),
        migrations.AlterField(
            model_name='specialization',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specializations', to='faculties.faculty'),
        ),
    ]
