# Generated by Django 6.0.6 on 2026-06-09 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculties', '0001_initial'),
        ('specializations', '0002_alter_specialization_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specialization',
            options={'ordering': ['faculty__name', 'name'], 'verbose_name': 'Mutaxassislik', 'verbose_name_plural': 'Mutaxassisliklar'},
        ),
        migrations.AddField(
            model_name='specialization',
            name='description',
            field=models.TextField(blank=True, verbose_name='Tavsif'),
        ),
        migrations.AddField(
            model_name='specialization',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='specialization',
            name='credits',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Kreditlar'),
        ),
        migrations.AlterField(
            model_name='specialization',
            name='degree_type',
            field=models.CharField(choices=[('bakalavr', 'Bakalavr'), ('magistr', 'Magistr'), ('doktorantura', 'Doktorantura')], default='bakalavr', max_length=20, verbose_name='Daraja'),
        ),
        migrations.AlterField(
            model_name='specialization',
            name='duration',
            field=models.PositiveSmallIntegerField(help_text='Muddat (oylarda)', verbose_name='Muddat'),
        ),
        migrations.AlterField(
            model_name='specialization',
            name='education_type',
            field=models.CharField(choices=[('kunduzgi', 'Kunduzgi'), ('sirtqi', 'Sirtqi'), ('kechki', 'Kechki'), ('masofaviy', 'Masofaviy')], max_length=20, verbose_name="Ta'lim shakli"),
        ),
        migrations.AlterField(
            model_name='specialization',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specializations', to='faculties.faculty', verbose_name='Fakultet'),
        ),
        migrations.AlterField(
            model_name='specialization',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Mutaxassislik nomi'),
        ),
    ]
