# Generated by Django 6.0.6 on 2026-06-09 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('specializations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Guruh nomi')),
                ('year_of_admission', models.PositiveSmallIntegerField(verbose_name='Qabul yili')),
                ('current_course', models.PositiveSmallIntegerField(default=1, verbose_name='Kurs')),
                ('student_count', models.PositiveSmallIntegerField(default=0, verbose_name='Talabalar soni')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='specializations.specialization', verbose_name='Mutaxassislik')),
            ],
            options={
                'verbose_name': 'Akademik guruh',
                'verbose_name_plural': 'Akademik guruhlar',
                'ordering': ['specialization', 'year_of_admission', 'name'],
            },
        ),
    ]
