# Generated by Django 5.0.3 on 2026-06-11 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academicgroup',
            options={'ordering': ['specialization__faculty__name', 'specialization__name', 'name'], 'verbose_name': 'Akademik guruh', 'verbose_name_plural': 'Akademik guruhlar'},
        ),
        migrations.AddField(
            model_name='academicgroup',
            name='language',
            field=models.CharField(choices=[('uzbek', "O'zbek"), ('russian', 'Rus'), ('english', 'Ingliz')], default='uzbek', max_length=20, verbose_name="Ta'lim tili"),
        ),
        migrations.AddField(
            model_name='academicgroup',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='academicgroup',
            name='current_course',
            field=models.PositiveSmallIntegerField(choices=[(1, '1-kurs'), (2, '2-kurs'), (3, '3-kurs'), (4, '4-kurs')], default=1, verbose_name='Kurs'),
        ),
        migrations.AlterUniqueTogether(
            name='academicgroup',
            unique_together={('name', 'year_of_admission')},
        ),
    ]
