# Generated by Django 6.0.6 on 2026-06-09 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Fan nomi')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Fan kodi')),
                ('subject_type', models.CharField(choices=[('general', 'Umumiy'), ('core', 'Asosiy'), ('elective', 'Tanlov'), ('professional', 'Professional')], default='core', max_length=20, verbose_name='Fan turi')),
                ('semester', models.PositiveSmallIntegerField(choices=[(1, '1-semestr'), (2, '2-semestr'), (3, '3-semestr'), (4, '4-semestr'), (5, '5-semestr'), (6, '6-semestr'), (7, '7-semestr'), (8, '8-semestr')], verbose_name='Semestr')),
                ('credits', models.PositiveSmallIntegerField(default=0, verbose_name='Kreditlar')),
                ('total_hours', models.PositiveIntegerField(default=0, verbose_name='Jami soatlar')),
                ('lecture_hours', models.PositiveIntegerField(default=0, verbose_name="Ma'ruza soatlari")),
                ('practical_hours', models.PositiveIntegerField(default=0, verbose_name='Amaliy soatlar')),
                ('lab_hours', models.PositiveIntegerField(default=0, verbose_name='Laboratoriya soatlari')),
                ('exam_type', models.CharField(choices=[('exam', 'Imtihon'), ('test', 'Test'), ('project', 'Loyiha')], default='exam', max_length=20, verbose_name='Imtihon turi')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='departments.department', verbose_name='Kafedra')),
            ],
            options={
                'verbose_name': 'Fan',
                'verbose_name_plural': 'Fanlar bazasi',
                'ordering': ['name'],
            },
        ),
    ]
