# Generated by Django 5.0.3 on 2026-06-11 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['department__name', 'semester', 'name'], 'verbose_name': 'Fan', 'verbose_name_plural': 'Fanlar bazasi'},
        ),
        migrations.AddField(
            model_name='subject',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='exam_type',
            field=models.CharField(choices=[('exam', 'Imtihon'), ('test', 'Test'), ('project', 'Loyiha'), ('coursework', 'Kurs ishi')], default='exam', max_length=20, verbose_name='Imtihon turi'),
        ),
    ]
